#!/usr/bin/env bash
#
# bootstrap things

DOTFILES_ROOT="$(pwd)"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  info 'setup gitconfig'

  git_credential='cache'

  user ' - What is your git author name?'
  read -e git_authorname
  user ' - What is your git author email?'
  read -e git_authoremail

  sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/.gitconfig.dist > git/.gitconfig

  success 'gitconfig'
}

setup_gitconfig

# Install Linux tools to have a nice working environment
if [ "$(uname -s)" == "Linux" ] && [ -f $(which apt-get)  ]
then
  info "apt-get detected - installing dependencies"
  sudo apt-get install xstow
else
  info "no apt-get detected - do it on your own"
fi

echo ''
echo '  All installed!'
